tdtinyurl.lo: /root/BITBUCKET/tdtinyurl/php_tdtinyurl/tdtinyurl.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/BITBUCKET/tdtinyurl/php_tdtinyurl $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/BITBUCKET/tdtinyurl/php_tdtinyurl/tdtinyurl.c -o tdtinyurl.lo 
$(phplibdir)/tdtinyurl.la: ./tdtinyurl.la
	$(LIBTOOL) --mode=install cp ./tdtinyurl.la $(phplibdir)

./tdtinyurl.la: $(shared_objects_tdtinyurl) $(TDTINYURL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_tdtinyurl) $(TDTINYURL_SHARED_LIBADD)

